### ISSUE TITLE
Security Problem Logs

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ml-serve#17]
JPL has issued the following SPLs:

- [ ] https://itsdb.jpl.nasa.gov/itsdb/spl/input_spl_ticket.cfm?spl_id=Q2629069
- [ ] https://itsdb.jpl.nasa.gov/itsdb/spl/input_spl_ticket.cfm?spl_id=Q2648287
- [ ] https://itsdb.jpl.nasa.gov/itsdb/spl/input_spl_ticket.cfm?spl_id=Q2648288
- [ ] https://itsdb.jpl.nasa.gov/itsdb/spl/input_spl_ticket.cfm?spl_id=Q2648289
- [ ] https://itsdb.jpl.nasa.gov/itsdb/spl/input_spl_ticket.cfm?spl_id=Q2648290
- [ ] https://itsdb.jpl.nasa.gov/itsdb/spl/input_spl_ticket.cfm?spl_id=Q2648291
- [ ] https://itsdb.jpl.nasa.gov/itsdb/spl/input_spl_ticket.cfm?spl_id=Q2648292
- [ ] https://itsdb.jpl.nasa.gov/itsdb/spl/input_spl_ticket.cfm?spl_id=Q2648293
- [ ] https://itsdb.jpl.nasa.gov/itsdb/spl/input_spl_ticket.cfm?spl_id=Q2648294

All must be fixed or the ML Serve app will be blocked.

**Comment by nutjob4life** [comment]
@asitang one easy way to close several of these SPLs is to have Ray Serve/FastAPI itself speak HTTPS instead of having Nginx do it and reverse-proxy to it.

Do you know if Ray Serve and/or FastAPI can speak HTTPS natively?

**Comment by asitang** [comment]
@nutjob4life I don't understand more of this :) , but I found this: https://fastapi.tiangolo.com/deployment/https/ and going to give it a read!

**Comment by asitang** [comment]
I also found this: https://www.slingacademy.com/article/deploying-fastapi-on-ubuntu-with-nginx-and-lets-encrypt/

**Comment by nutjob4life** [comment]
Update: forced to shut down ML Serve on edrn-labcas in order to keep JPLNet from taking the entire system away.

**Comment by nutjob4life** [comment]
More updates:

- https://fastapi.tiangolo.com/deployment/https/ … yes this would be ideal, except we're just having Nginx (the "TLS Termination") reverse-proxy to FastAPI (on "localhost") and we have to speak TLS on localhost, so Nginx is redundant and JPL's rule is that any HTTP server (even on "localhost") must speak `https`.
- https://www.slingacademy.com/article/deploying-fastapi-on-ubuntu-with-nginx-and-lets-encrypt/ … this is overkill since a self-signed certificate for "localhost" is sufficient—no need for "Let's Encrypt".
- https://towardsdatascience.com/how-to-deploy-a-secure-api-with-fastapi-docker-and-traefik-b1ca065b100f … not even going to bother since Docker is forbidden on `edrn-labcas`

I think the correct approach is to use [Uvicorn](https://www.uvicorn.org) with [https](https://www.uvicorn.org/settings/#https) and a self-signed certificate and ensure it binds solely to localhost.

the issue we just need something that binds to localhost only and has TLS 1.2 enabled. A self-signed certificate is fine, so we don't need to bother with "Let's Encrypt". We can't use Docker+Traefik since Docker is forbidden. A

**Comment by nutjob4life** [comment]
This is over a year old and ML serve hasn't even been running since 2024-01-06. So

- Closing this issue
- Removing ml-serve from Alleviam monitoring
- Preventing restarting of ml-serve on `edrn-docker`
